# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'SIDPOC(b39446a1-bcbd-4ea9-aad2-13007cb57bc1)'
    appType: 'webApp'
    appName: 'azuredevops'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'SIDPOC(b39446a1-bcbd-4ea9-aad2-13007cb57bc1)'
    appType: 'webApp'
    appName: 'azuredevops'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
